parameters:
    locale: '%env(resolve:DEFAULT_LOCALE)%'
    web_path: '%kernel.root_dir%/../public'
    api_domain: 'http://local.acme.com'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: false
        autoconfigure: false
        public: true
    
    App\Command\:
        resource: '%kernel.project_dir%/src/Command/*'
        public: true
        autowire: true
        autoconfigure: true
        tags: [ 'console.command' ]
    
    App\DataFixtures\ORM\:
        resource: '%kernel.project_dir%/src/DataFixtures/ORM/*'
        autowire: true
        autoconfigure: true
    
    App\Repository\:
        resource: '%kernel.project_dir%/src/Repository/*'
        public: true
        autowire: true
        autoconfigure: true
        tags: [ 'doctrine.repository_service' ]
    
    ## TOKEN ##
    app.token.authenticator:
        class: App\Security\TokenAuthenticator
        arguments:
            $em: '@doctrine.orm.entity_manager'
            $jwtEncoder: '@lexik_jwt_authentication.encoder'

    ## MANAGERS ##
    app.manager.promotion:
        class: App\Manager\PromotionManager
        arguments:
            $em: '@doctrine.orm.entity_manager'
    
    app.manager.order:
        class: App\Manager\OrderManager
        arguments:
            $em: '@doctrine.orm.entity_manager'
            $promotionManager: '@app.manager.promotion'
            $taxManager: '@app.manager.tax'
            
    app.manager.product:
        class: App\Manager\ProductManager
        arguments:
            $em: '@doctrine.orm.entity_manager'
            
    app.manager.tax:
        class: App\Manager\TaxManager

    ## PROMOTIONS ##
    app.promotion.promotion_type:
        class: App\Model\AbstractPromotion
        arguments:
            $em: '@doctrine.orm.entity_manager'
        abstract: true

    app.promotion.promotion_type.buy_x_for_y:
        autowire: false
        autoconfigure: false
        public: true
        class: App\Model\Promotion\BuyXForYPromotion
        parent: app.promotion.promotion_type
        tags:
            - {name: app.promotion.promotion}

    app.promotion.promotion_type.buy_x_for_y_quantity:
        autowire: false
        autoconfigure: false
        public: true
        class: App\Model\Promotion\BuyXForYQuantityPromotion
        parent: app.promotion.promotion_type
        tags:
            - {name: app.promotion.promotion}

    app.promotion.promotion_type.event_sale:
        autowire: false
        autoconfigure: false
        public: true
        class: App\Model\Promotion\EventSalePromotion
        parent: app.promotion.promotion_type
        tags:
            - {name: app.promotion.promotion}

