services:
    # default configuration for services in *this* file
    _defaults:
        autowire: false
        autoconfigure: false
        public: true
    
    Acme\Bundle\UserBundle\DataFixtures\ORM\:
        resource: '%kernel.project_dir%/src/Acme/Bundle/UserBundle/DataFixtures/ORM/*'
        autowire: true
        autoconfigure: true
    
    Acme\Bundle\UserBundle\Repository\:
        resource: '%kernel.project_dir%/src/Acme/Bundle/UserBundle/Repository/*'
        public: true
        autowire: true
        autoconfigure: true
        tags: [ 'doctrine.repository_service' ]